In [247]:
import torch.nn as nn
import torch
import torch.optim as optim
import numpy as np

In [248]:
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68., 97, 70]], 
                  dtype='float')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float')

inputs = torch.tensor(inputs)

targets = torch.tensor(targets)



In [249]:
from torch.utils.data import TensorDataset
train_ds= TensorDataset(inputs,targets)

In [250]:
from torch.utils.data import DataLoader
batch  = 5
train_dl = DataLoader(train_ds, batch_size=batch, shuffle=True)

In [251]:
model  = nn.Linear(3,2)
print(model.weight , model.bias)

Parameter containing:
tensor([[-0.0248,  0.3709, -0.0859],
        [ 0.5715,  0.3178, -0.3477]], requires_grad=True) Parameter containing:
tensor([-0.0138, -0.3458], requires_grad=True)


In [252]:
pred = model(inputs)
pred

tensor([[19.3318, 47.7126],
        [24.8700, 57.3708],
        [42.5441, 71.7901],
        [10.2284, 58.7444],
        [27.8663, 45.2545],
        [18.9362, 47.9662],
        [24.4132, 56.7053],
        [42.4334, 72.0139],
        [10.6240, 58.4907],
        [27.8051, 44.3353],
        [18.8750, 47.0471],
        [24.4744, 57.6245],
        [43.0008, 72.4556],
        [10.2896, 59.6636],
        [28.2619, 45.0008]], grad_fn=<AddmmBackward0>)

In [253]:
import torch.nn.functional  as F
loss_fn   = F.mse_loss
loss= loss_fn(model(inputs), targets)
loss

tensor(2812.0732, grad_fn=<MseLossBackward0>)

In [257]:
opt =  optim.SGD(model.parameters(), lr=.001)
opt

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    fused: None
    lr: 0.001
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)

In [258]:
def fit(num_epochs, model, loss_fn, opt, train_dl):
    for epoch in range(num_epochs):
        for xb,yb in trail_dl:
            pred = model(xb)
            loss = loss_fn(pred , yb)
            loss.backward()
            opt.step()
            opt.zero_grad()
            if (epoch+1) % 10 == 0:
                print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))
                

In [259]:
fit(100, model, loss_fn, opt, train_dl)


Epoch [10/100], Loss: nan
Epoch [10/100], Loss: nan
Epoch [10/100], Loss: nan
Epoch [20/100], Loss: nan
Epoch [20/100], Loss: nan
Epoch [20/100], Loss: nan
Epoch [30/100], Loss: nan
Epoch [30/100], Loss: nan
Epoch [30/100], Loss: nan
Epoch [40/100], Loss: nan
Epoch [40/100], Loss: nan
Epoch [40/100], Loss: nan
Epoch [50/100], Loss: nan
Epoch [50/100], Loss: nan
Epoch [50/100], Loss: nan
Epoch [60/100], Loss: nan
Epoch [60/100], Loss: nan
Epoch [60/100], Loss: nan
Epoch [70/100], Loss: nan
Epoch [70/100], Loss: nan
Epoch [70/100], Loss: nan
Epoch [80/100], Loss: nan
Epoch [80/100], Loss: nan
Epoch [80/100], Loss: nan
Epoch [90/100], Loss: nan
Epoch [90/100], Loss: nan
Epoch [90/100], Loss: nan
Epoch [100/100], Loss: nan
Epoch [100/100], Loss: nan
Epoch [100/100], Loss: nan


In [292]:
import torch
import torch.nn as nn
import torch.optim as optim

# Check if GPU is available
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Example data
n_samples = 100
n_features = 3
n_targets = 2

# Generate random data for inputs (X) and targets (y)
X = torch.randn(n_samples, n_features).to(device)  # Move to GPU
true_weights = torch.tensor([[1.0, -2.0, 3.0], [4.0, -5.0, 6.0]]).to(device)
true_biases = torch.tensor([7.0, 8.0]).to(device)
y = X @ true_weights.T + true_biases + torch.randn(n_samples, n_targets).to(device)  # Add some noise

# Model definition
class LinearRegressionModel(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(LinearRegressionModel, self).__init__()
        self.linear = nn.Linear(input_dim, output_dim)
    
    def forward(self, x):
        return self.linear(x)

# Initialize model, loss function, and optimizer
input_dim = n_features
output_dim = n_targets
model = LinearRegressionModel(input_dim, output_dim).to(device)  # Move model to GPU
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.09)

# Training loop
num_epochs = 100000
for epoch in range(num_epochs):
    # Zero the gradients
    optimizer.zero_grad()
    
    # Forward pass
    outputs = model(X)
    
    # Compute loss
    loss = criterion(outputs, y)
    
    # Backward pass and optimization
    loss.backward()
    optimizer.step()
    
    # Print progress
    if epoch % 10000 == 0:
        print(f'Epoch [{epoch}/{num_epochs}], Loss: {loss.item():.4f}')
     

# Print final weights and biases
final_weights = model.linear.weight.data
final_biases = model.linear.bias.data
print(f'Final weights: {final_weights}')
print(f'Final biases: {final_biases}')


Epoch [0/100000], Loss: 94.7377
Epoch [10000/100000], Loss: 0.9080
Epoch [20000/100000], Loss: 0.9080
Epoch [30000/100000], Loss: 0.9080
Epoch [40000/100000], Loss: 0.9080
Epoch [50000/100000], Loss: 0.9080
Epoch [60000/100000], Loss: 0.9080
Epoch [70000/100000], Loss: 0.9080
Epoch [80000/100000], Loss: 0.9080
Epoch [90000/100000], Loss: 0.9080
Final weights: tensor([[ 1.0707, -2.0256,  3.0897],
        [ 3.9250, -4.9976,  6.1647]], device='cuda:0')
Final biases: tensor([7.2407, 8.1460], device='cuda:0')


In [286]:
X[0] , y[0]


(tensor([-0.6311, -0.2593, -0.6905], device='cuda:0'),
 tensor([4.4702, 3.4434], device='cuda:0'))

In [287]:
X[0]@final_weights.T+final_biases

tensor([4.6959, 2.5014], device='cuda:0')