In [6]:
import torch 
import numpy as np

# nn
import torch.nn as nn


In [8]:
a = torch.FloatTensor(3,2)
a

tensor([[9.6766e+24, 1.7362e-42],
        [0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00]])

## CUDA

In [13]:
cuda_tesor =  a.to('cuda')
cuda_tesor

tensor([[9.6766e+24, 1.7362e-42],
        [0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00]], device='cuda:0')

## NN

In [17]:
layer =  nn.Linear(2,5)
vector = torch.FloatTensor([0,1])
layer(vector)

tensor([-0.7949, -0.1743,  0.3680, -1.0271,  0.0277], grad_fn=<ViewBackward0>)

In [26]:
s= nn.Sequential(
    nn.Linear(2,5),
    nn.ReLU(),
    nn.Linear(5,20),
    nn.ReLU(),
    nn.Linear(20,10),
    nn.Dropout(p = .3),
    nn.Softmax(dim =1)
)
s(torch.FloatTensor([[1,2]]))

tensor([[0.1397, 0.1015, 0.0659, 0.1327, 0.0937, 0.1015, 0.1015, 0.1015, 0.1002,
         0.0616]], grad_fn=<SoftmaxBackward0>)